import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div
          style={{
            "background-image":
              "radial-gradient( circle 2000px at 9% 80.3%,  rgba(55,60,245,1) 0%, rgba(234,161,15,0.90) 100.2%)",
          }}
          className='relative w-screen h-screen'
        >
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
